### ISSUE TITLE
Add: 'Quantitative Politics with R'

### ISSUE THREAD

**Issue by erikgahner** [oscarbaruffa/BigBookofR#13]
Suggestion for field specific book:

## Quantitative Politics with R

[Erik Gahner Larsen](https://twitter.com/erikgahner) & [Zoltán Fazekas](https://twitter.com/fazol)

An introduction to quantitative analysis of political data in R

http://qpolr.com/

**Comment by oscarbaruffa** [comment]
added, thanks!
