### ISSUE TITLE
Add Tidyverse Skills for DS

### ISSUE THREAD

**Issue by oscarbaruffa** [oscarbaruffa/BigBookofR#131]
https://leanpub.com/tidyverseskillsdatascience

**Comment by mattroumaya** [comment]
This seems like the same/similar resource, might be an update instead of an add: https://www.bigbookofr.com/r-programming.html#tidyverse-skills-for-data-science

**Comment by oscarbaruffa** [comment]
Indeed it is! Thanks! I'll add the link to this format alongside the others
