### ISSUE TITLE
add best coding practices in R

### ISSUE THREAD

**Issue by vikram-rawat** [oscarbaruffa/BigBookofR#157]
## [best coding practices in R]

[Vikram Singh Rawat] - https://twitter.com/Guru_GyanKhoji

[book contains a compilation of best practices for R that you will need to write and maintain better r code]

It's a freely available book.

(https://bookdown.org/content/d1e53ac9-28ce-472f-bc2c-f499f18264a3/)

**Comment by oscarbaruffa** [comment]
added
