### ISSUE TITLE
Add archeological book

### ISSUE THREAD

**Issue by oscarbaruffa** [oscarbaruffa/BigBookofR#160]
https://benmarwick.github.io/How-To-Do-Archaeological-Science-Using-R/

**Comment by bbartholdy** [comment]
And https://www.cambridge.org/core/books/quantitative-methods-in-archaeology-using-r/DEAE593FA2418EA3B8ECD538C34ED2D5
Paid - I will have to check the price when I'm not on my University's network.

There's no real consensus where archaeology belongs as a discipline, so it would be nice if it gets it's own chapter (I will try to find more books).

**Comment by oscarbaruffa** [comment]
Thanks :). Ive found two I think so can def get it's own chapter :)
Regards,

*Oscar *

**Comment by bbartholdy** [comment]
Oops, didn't see the other issue haha. Great!

**Comment by oscarbaruffa** [comment]
added
