### ISSUE TITLE
add twitter accounts

### ISSUE THREAD

**Issue by mohit2152sharma** [oscarbaruffa/BigBookofR#165]
Just as a suggestion, not sure if it is worth adding as a separate section, but there are couple of twitter accounts which are worth following from a beginner's perspective as they post regular content. For example:

1. [R posts you might have missed](https://twitter.com/icymi_r)
2. [#RStats question a day](https://twitter.com/data_question)
3. [R function a day](https://twitter.com/rfunctionaday)
4. [Rstats](https://twitter.com/rstatstweet)

(full disclosure: I manage the account #RStats question a day)

**Comment by oscarbaruffa** [comment]
thanks! I think a better place will be to add them in the t4rstats.com book, which I'll do :)
