### ISSUE TITLE
NHS-R Community Book club

### ISSUE THREAD

**Issue by Lextuga007** [oscarbaruffa/BigBookofR#175]
Happy to do a pull request for this but I wondered if I could expand on the NHS-R Community Book club in the book? The community is open to all public sector employees and organisations who are close to the NHS like Charities, Voluntary Sector and Academics. The Slack url is nhsrcommunity.slack.com and it's set to allow some email addresses automatically but if anyone requires access they can contact the NHS-R community through https://nhsrcommunity.com/contact/. 

I've added the BigBookofR to the introduction to R and R Studio course I run for the Community: https://lextuga007.github.io/intro_r/10-workshop-learning.html#9 as it's a great resource! Thanks so much for this and adding NHS-R Community links to it.

**Comment by oscarbaruffa** [comment]
Its a pleasure :). Yes please add the info via a PR - much easier for me
but if you don't get to it I'll eventually get round to it :).
Regards,

*Oscar *

**Comment by oscarbaruffa** [comment]
added
