### ISSUE TITLE
Add Text mining for professionals

### ISSUE THREAD

**Issue by oscarbaruffa** [oscarbaruffa/BigBookofR#255]
See DM and other issue

**Comment by oscarbaruffa** [comment]
added

**Comment by manika-lamba** [comment]
Please update the link to: https://www.amazon.com/Text-Mining-for-Information-Professionals_-An-Uncharted-Territory/dp/3030850846

**Comment by oscarbaruffa** [comment]
thanks its updated https://www.bigbookofr.com/text-analysis.html#text-mining-for-information-professionals-an-uncharted-territory
