### ISSUE TITLE
Update 16.10 Introduction to Data Analysis with R

### ISSUE THREAD

**Issue by jmbuhr** [oscarbaruffa/BigBookofR#257]
Hi there :)
Since I added my course at https://www.bigbookofr.com/life-sciences.html, 16.10 Introduction to Data Analysis with R,
I updated the content and re-recorded it with a fancy new microphone for crisp audio.
The link to the new version is: https://jmbuhr.de/dataintro/

**Comment by oscarbaruffa** [comment]
Thanks, i've updated the link! 

https://www.bigbookofr.com/life-sciences.html#introduction-to-data-analysis-with-r
