### ISSUE TITLE
Library of Statistical Techniques (LOST)

### ISSUE THREAD

**Issue by erictleung** [oscarbaruffa/BigBookofR#264]
> LOST is a publicly-editable website with the goal of making it easy to execute statistical techniques in statistical software.
>
> Each page of the website contains a statistical technique — which may be an estimation method, a data manipulation or cleaning method, a method for presenting or visualizing results, or any of the other kinds of things that statistical software typically does.

Contains both R and Python code.

Link: https://lost-stats.github.io/

**Comment by oscarbaruffa** [comment]
Looks really cool, thanks Eric. It's in the que!
Regards,

*Oscar *

**Comment by oscarbaruffa** [comment]
cool added soon
