### ISSUE TITLE
Include new book: R for Health Data Science

### ISSUE THREAD

**Issue by riinuots** [oscarbaruffa/BigBookofR#272]
Hi! 

Thanks so much for this amazing resource!

This should go under "Field specific":
**R for Health Data Science**

R for Health Data Science includes everything a healthcare professional needs to go from R novice to R guru. By the end of this book, you will be taking a sophisticated approach to health data science with beautiful visualisations, elegant tables, and nuanced analyses. Keywords: health, healthcare, medical, medicine, clinical.

Available at: https://argoshare.is.ed.ac.uk/healthyr_book/

Thank you!
Best wishes,
Riinu

**Comment by oscarbaruffa** [comment]
Thanks Riinu,

Great work on the book! I've already included it in Life Sciences though.
Still think it should also be in Field Specific?

https://www.bigbookofr.com/life-sciences.html#r-for-health-data-science

Regards,

*Oscar *

**Comment by riinuots** [comment]
So sorry! I did do a search but missed it. Yes life sciences absolutely fine. Should not have doubted this great resource :)

If you could fix the type in Ewen's first name and this is the correct Twitter profile: https://twitter.com/ewenharrison

Thanks again!
Best wishes,
Riinu

**Comment by oscarbaruffa** [comment]
Yeah the search bar isnt that fantastic.

Thanks for pointing out the type and link, fixed now.
Regards,

*Oscar *
