### ISSUE TITLE
gt cookbook link

### ISSUE THREAD

**Issue by slodge** [oscarbaruffa/BigBookofR#292]
Hi

The gt cookbook link looks incorrect (I guess they moved it!)

It should be 2 links:
- https://themockup.blog/static/resources/gt-cookbook.html
- https://themockup.blog/static/resources/gt-cookbook-advanced.html

Thanks for maintaining this!

Stuart

**Comment by oscarbaruffa** [comment]
Thank so much! Will update
Regards,

*Oscar *

**Comment by oscarbaruffa** [comment]
pending add
