### ISSUE TITLE
Reproducible statistics for psychologists with R

### ISSUE THREAD

**Issue by llrs** [oscarbaruffa/BigBookofR#297]
[Reproducible statistics for psychologists with R](https://crumplab.com/rstatsforpsych/index.html)

"Reproducible statistics for psychologists with R: Lab Tutorials" was written by Matthew J. C. Crump.

**Comment by oscarbaruffa** [comment]
Thanks! Its in the que and will be added soon

**Comment by oscarbaruffa** [comment]
added, thanks!
