### ISSUE TITLE
Computational Social Science & Applied Data Visualization

### ISSUE THREAD

**Issue by opop999** [oscarbaruffa/BigBookofR#300]
Dear Oscar,
thank you very much for your contributions to the R community! 

I recently came across two books from Paul C. Bauer and I see that they are not yet in the compendium. Specifically, they are more of "course companions", however, they can be read as normal publications. 

Hope they might be of interest.

[Computational Social Science: Theory & Application](https://bookdown.org/paul/2021_computational_social_science)

[Applied Data Visualization](https://bookdown.org/paul/applied-data-visualization/)

**Comment by oscarbaruffa** [comment]
Thanks, I'll add them to the que!

**Comment by oscarbaruffa** [comment]
added
