### ISSUE TITLE
A Little Book of R for Bioinformatics 2.0

### ISSUE THREAD

**Issue by sergbolshakov** [oscarbaruffa/BigBookofR#335]
## A Little Book of R for Bioinformatics 2.0

[Book](https://brouwern.github.io/lbrb/)

[Source Code](https://github.com/brouwern/lbrb)

This book is based on the original [A Little Book of R for Bioinformatics](https://a-little-book-of-r-for-bioinformatics.readthedocs.io/en/latest/) by Dr. Avril Coghlan (Hereafter “ALBRB 1.0”). Dr. Coghlan’s book was one of the first and most thorough introductions to using R for bioinformatics and computational biology, and was generously published under the Creative Commons 3.0 Attribution License [(CC BY 3.0)](https://creativecommons.org/licenses/by/3.0/). In addition to describing how to do bioinformatics in R, Coghlan provided numerous R functions to facilitate important tasks, practice questions, and references to further reading.

[ALBRB 1.0](https://a-little-book-of-r-for-bioinformatics.readthedocs.io/en/latest/) was extremely useful to me when I was learning bioinformatics and computational biology. In this version of the book, which I’ll refer to as ALBRB 2.0, I have adapted Dr. Coghlan’s original book to suit my own teaching needs, updated it with current packages now available in R, added background materials from other open-access sources, and added in my original materials.

Below I’ve outlined the general types of changes I’ve made to the original book. I have tried to link back to the original content that these updates are derived from and note how changes were made. Any errors or inconsistencies should be ascribed to me, not Dr. Coghlan. If you have any feedback, please email me at [brouwern@gmail.com](mailto:brouwern@gmail.com)

~Nathan Brouwer, June 2021

Changes implemented in ALBRB 2.0 by Nathan Brouwer

- Converted the entire book to RMarkdown and published it via bookdown.
- Added instructions for using RStudio and RStudio Cloud.
- Updated instructions to reflect any changes in software, including changes to how the bioinformatics repository Bioconductor works circa 2021.
- Split up chapters into smaller units.
- Reorganized the order of some material.
- Added biological background information by integrating information from the Open Access textbook [LibreText General Biology](https://bio.libretexts.org/Bookshelves/Introductory_and_General_Biology/Book%3A_General_Biology_(OpenStax))
- Added links to the books I am developing, Get R Done! and Computational Biology for All.
- Moved functions written by Coghlan and datasets to my teaching package [compbio4all](https://github.com/brouwern/compbio4all).
- Functions names changed from camelCase to snake_case
- Functions re-written so as not to use Bioconductor to reduce/eliminate dependency of compbio4all on Bioconductor.
- Changed some plotting to ggplot2 or ggpubr.
- Added additional subheadings
- Added vocab and function lists to the beginning of many chapters
- At times replaced non-biological examples with biological ones.
- Change from British to American English (Sorry! Couldn’t help myself - the spellchecker made me do it!)
- Provided additional links to external resources.
- Added use of rentrez for querying NCBI databases

**Comment by Ohlsen** [comment]
Thanks, i added the book to the next release.
