### ISSUE TITLE
Spatial Data Science with applications in R has moved 

### ISSUE THREAD

**Issue by defuneste** [oscarbaruffa/BigBookofR#338]
Hello, 

Spatial Data Science with applications in R has moved (Bivand and Pebesma) (https://www.bigbookofr.com/geospatial.html#spatial-data-science)

It was here: https://keen-swartz-3146c4.netlify.app/

And it is now here: https://r-spatial.org/book/

The first link is still working as a redirection.

**Comment by oscarbaruffa** [comment]
thanks for that, I've updated it!
