### ISSUE TITLE
Starred / Recomended resources?

### ISSUE THREAD

**Issue by lepras** [oscarbaruffa/BigBookofR#342]
Can we have a star aside a resource recommended by you or to symbolize "An essential resource". I think this is meant as a repo and ofcource if you have added a resource, you probably have done your due diligence but some category pages are quite overwhelming to be honest.

**Comment by oscarbaruffa** [comment]
Hi,

I've thought about this but it's quite hard to recommend books for a
category.

Yes some categories are indeed overwhelming as they have a lot of chapters,
but I am planning on on an upgrade (
https://oscarbaruffa.com/bigbookofrupgrade/) which will help me remove
outdated books which should slim them down.

For very large categories (like with R programming for example, Im
thinking of splitting them between base R and tidyverse) and for the Data
Science and stats one's also reducing them further - but what groups to
create is the problem. I would welcome any suggestions!
