### ISSUE TITLE
Linear Algebra for Data Science, by Shaina Race Bennett

### ISSUE THREAD

**Issue by jimrothstein** [oscarbaruffa/BigBookofR#363]
https://shainarace.github.io/LinearAlgebra/index.html

Covers a range of linear algebra topics of use to data science; uses R.
Not a proof, theory or abstraction type of book, but does not spoon feed either.   
Gets to what one needs to know.   I found enjoyable to read.

**Comment by oscarbaruffa** [comment]
thanks, it'll be in the next update!
