### ISSUE TITLE
The Analysis of Data - Guy Lebanon

### ISSUE THREAD

**Issue by jimrothstein** [oscarbaruffa/BigBookofR#368]
Book:   http://theanalysisofdata.com/book/

This is a math book that uses R.  .   By abstracting and clearly defining ideas and relationships, math  can actually clarify ! 
This is an undergrad book, but not as heavy on proofs, abstractions as other math books.   Uses R.

From the Preface:

This volume focuses on probability theory. There are many excellent textbooks on probability, and yet this book differs from others in several ways.

    Probability theory is a wide field. This book focuses on the parts of probability that are most relevant for statistics and machine learning.
    The book contains almost all of the mathematical prerequisites, including set theory, metric spaces, linear algebra, differentiation, integration, and measure theory.
    Almost all results in the book appear with a proof.
    Probability textbooks are typically either elementary or advanced. This book strikes a balance by attempting to avoid measure theory where possible, but resorting to measure theory and other advanced material in a few places where they are essential.
    The book uses R to illustrate concepts. Full code is available in the book, facilitating reproducibility of experiments and letting readers experiment with variations of the code.

**Comment by oscarbaruffa** [comment]
looks to be a bit outdated so wont be adding (also quite hard to read). Thank you for submitting!
