### ISSUE TITLE
One more e-book on psychometrics

### ISSUE THREAD

**Issue by gungorMetehan** [oscarbaruffa/BigBookofR#396]
**30.17 R Programming for Psychometrics**

by [Susu Zhang](https://psychology.illinois.edu/directory/profile/szhan105)

A good test developer should not only be well-versed with measurement theory and psychometric methods. Nowadays, programming skills are also essential. So, the aim of this book is to introduce R to you and improve your data wrangling and functional programming skills.

Link: https://bookdown.org/sz_psyc490/r4psychometics/

**Comment by oscarbaruffa** [comment]
these are great additions, all in the que for next release!
