### ISSUE TITLE
Modern Statistical Methods for Psychology

### ISSUE THREAD

**Issue by gungorMetehan** [oscarbaruffa/BigBookofR#397]
**30.15 Modern Statistical Methods for Psychology**

by [Mine Çetinkaya-Rundel](http://mine-cr.com/), [Johanna Hardin](https://research.pomona.edu/johardin/)

This book is intended to help psychology students build a foundation for statistical thinking and methods. This textbook consists of 3 main parts: (1) descriptive statistics, (2) foundations for inference, and (3) statistical inference. Each part contains multiple chapters. Each chapter ends with a review section which contains a chapter summary as well as a list of key terms introduced in the chapter.

Link: https://bookdown.org/gregcox7/ims_psych/

**Comment by oscarbaruffa** [comment]
also added, thanks!
