### ISSUE TITLE
Data Wrangling and Visualization Guide

### ISSUE THREAD

**Issue by gungorMetehan** [oscarbaruffa/BigBookofR#398]
**12.9 Data Wrangling and Visualization Guide**

by Max Ricciardelli

'Data Wrangling and Visualization Guide' contains modules on programming and data visualization. These modules are here to present a succinct guide to using R, RStudio, and R Markdown for data wrangling and visualization. This guide is meant for those who have little to no experience in programming.

Link: https://bookdown.org/max_ricciardelli/wrangling_modules/

**Comment by oscarbaruffa** [comment]
added, thank you!
