### ISSUE TITLE
Ciencia de Datos para Gente Sociable, by Antonio Vazquez Brust

### ISSUE THREAD

**Issue by pablotis** [oscarbaruffa/BigBookofR#401]
Link: https://bitsandbricks.github.io/ciencia_de_datos_gente_sociable/

*Presentación:* 
`
Este libro fue escrito con una audiencia en mente formada por urbanistas, sociólogos, politólogas y otros entusiastas que se acercan al tema desde las Ciencias Sociales. Aún así, y por supuesto, todas las personas y algoritmos con capacidad de procesar lenguaje son bienvenidas.
`

**Comment by oscarbaruffa** [comment]
added
