### ISSUE TITLE
Suggested book: Data Science Live Book (by Pablo Casas)

### ISSUE THREAD

**Issue by jmcastagnetto** [oscarbaruffa/BigBookofR#408]
URL: https://livebook.datascienceheroes.com/
Author: Pablo Casas
Publication date: January 2019

> "...
> The book will facilitate the understanding of common issues when data analysis and machine learning are done.
> 
> Building a predictive model is as difficult as one line of R code:
> 
> ```r
> my_fancy_model=randomForest(target ~ var_1 + var_2, my_complicated_data)
> ```
> 
> That’s it.
> 
> But, data has its dirtiness in practice. We need to sculp it, just like an artist does, to expose its information in order to find answers (and new questions).
> 
> There are many challenges to solve, some data sets requiere more sculpting than others. Just to give an example, random forest does not accept empty values, so what to do then? Do we remove the rows in conflict? Or do we transform the empty values into other values? What is the implication, in any case, to my data?
> 
> Despite the empty values issue, we have to face other situations such as the extreme values (outliers) that tend to bias not only the predictive model itself, but the interpretation of the final results. It’s common to “try and guess” how the predictive model considers each variable (ranking best variables), and what the values that increase (or decrease) the likelihood of some event to happening (profiling variables) are.
> 
> Deciding the data type of the variables may not be trivial. A categorical variable could be numerical and viceversa, depending on the context, the data, and the algorithm itself (some of which only handle one data type). The conversion also has its own implications in how the model sees the variables.
> 
> It is a book about data preparation, data analysis and machine learning. Generally in literature, data preparation is not as popular as the creation of machine learning models.
> ..."

**Comment by oscarbaruffa** [comment]
Thanks @jmcastagnetto. In this case I wont be adding the book, only because its at the threshold of being ~5 years old, and theres already A LOT of books in the Data Science category. I'm sorry to not be adding this book, but please submit others you come across.
