### ISSUE TITLE
Suggested book: Bayes Rules! An Introduction to Applied Bayesian Modeling

### ISSUE THREAD

**Issue by jmcastagnetto** [oscarbaruffa/BigBookofR#409]
URL: https://www.bayesrulesbook.com/
Authors: Alicia A. Johnson, Miles Q. Ott, Mine Dogucu
Publication date: 2021-12-01
 
> "...
> Statistics and data science focus on using data to learn about the world and make predictions. The Bayesian approach gives a principled, powerful tool for obtaining probabilities and predictions about our unknown quantities of interest, given what we do know (the data). It gives easy-to-interpret results that directly quantify our uncertainties. Unfortunately, it is rarely taught in depth at the undergraduate level, perhaps out of concern that there would be too many scary-looking integrals to do or too much cryptic code to write.
> 
> Bayes Rules! shows that the Bayesian approach is in fact accessible to students and self-learners with basic statistics knowledge, even if they are not adept at calculus derivations or coding up fancy algorithms from scratch. The book achieves this with many reader-friendly features, such as clear explanations through words and pictures, quizzes to test your understanding, and the bayesrules R package that contains datasets and functions that facilitate trying out Bayesian methods.
> ..."

**Comment by oscarbaruffa** [comment]
thanks @jmcastagnetto , the book is already in the collection. Keep them coming though! https://www.bigbookofr.com/statistics#bayes-rules
