### ISSUE TITLE
R Programming for Actuarial Science

### ISSUE THREAD

**Issue by Micromantic** [oscarbaruffa/BigBookofR#410]
https://www.wiley.com/en-ae/R+Programming+for+Actuarial+Science-p-9781119754992

R Programming for Actuarial Science
Professional resource providing an introduction to R coding for actuarial and financial mathematics applications, with real-life examples

R Programming for Actuarial Science provides a grounding in R programming applied to the mathematical and statistical methods that are of relevance for actuarial work.

**Comment by oscarbaruffa** [comment]
thanks! It will be in the next release

**Comment by oscarbaruffa** [comment]
added
