### ISSUE TITLE
Causal inference in R

### ISSUE THREAD

**Issue by KittJonathan** [oscarbaruffa/BigBookofR#426]
Hi ! 

This book is mentioned in the Posit conf 2024 workshop on causal inference. Just had a quick look at the contents, which seem pretty neat!

[https://www.r-causal.org/](https://www.r-causal.org/)

**Comment by oscarbaruffa** [comment]
thanks! It's in the que

**Comment by oscarbaruffa** [comment]
added

**Comment by KittJonathan** [comment]
Thanks!
