### ISSUE TITLE
"28.42 Tidy Evaluation" resource no longer seems to exist

### ISSUE THREAD

**Issue by tjkelman** [oscarbaruffa/BigBookofR#461]
Points to an old tidyeval guide @ URL: https://tidyeval.tidyverse.org/

...which results in a DNS error on my end.  Couldn't find the issue already reported, so doing so now.  Many thanks!

**Comment by oscarbaruffa** [comment]
thanks @tjkelman for pointing out the broken link. I have decided to remove the book entirely, it has been superseded some time ago and I guess they didnt want to keep that domain going. See: https://github.com/tidyverse/tidyeval
