### ISSUE TITLE
add bio section

### ISSUE THREAD

**Issue by oscarbaruffa** [oscarbaruffa/BigBookofR#6]
Looks great!  Maybe you could add a Biology section with Orchestrating Single-Cell Analysis with Bioconductor (https://osca.bioconductor.org) and Modern Statistics for Modern Biology (https://huber.embl.de/msmb/) - both written in Bookdown

**Comment by oscarbaruffa** [comment]
Mike Smith
@grimbough
·
43m
Replying to 
@OscarBaruffa
Looks great!  Maybe you could

**Comment by oscarbaruffa** [comment]
added the first one to Field Specific Section, second ones link doest work

**Comment by grimbough** [comment]
Since Twitter is quite insistent that it wants to edit the URL, the full link for the second book is https://www.huber.embl.de/msmb/
